### ISSUE TITLE
No xrandr on Chromeos?

### ISSUE THREAD

**Issue by entrity** [Varpie/chroscreen#2]
Can you help me understand this? I am trying to run it on my chromebook, and I find that there is no xrandr executable.

1. I open a developer console by hitting Ctrl+Alt+T
1. I enter `shell` to start GNU bash
1. I try to execute `./chroscreen`
1. I get an error: `bash: xrandr: command not found`

**Comment by Varpie** [comment]
I have seen that too. It used to work, but I believe an upgrade removed xrandr from ChromeOS, since a few weeks it also shows me this error. If this is the case, I'm afraid there is nothing to do except wait for Google to put back xrandr.

**Comment by Varpie** [comment]
After doing some digging, I found out Google replaced X11 by freon in order to remove dependencies and get to a lower level.  
You can see more infos on [this G+ post](https://plus.google.com/+FrancoisBeaufort/posts/L3zmATV8BW5).  
Unfortunately, that means xrandr is not usable anymore.
